Repository notqmail/notqmail, pull requests merged in 2019-07, with the labels that each got.

#4 honor DESTDIR on install
  CHANGES
  Makefile
  install.c
Labels: packaging

#24 Fix build on utmpx-only systems, such as FreeBSD.
  CHANGES
  FILES
  Makefile
  TARGETS
  qbiff.c
  qtmp.h1
  qtmp.h2
  tryutmpx.c
Labels: build

#20 Add missing includes
  Makefile
  qmail-lspawn.c
  qmail-qmqpd.c
Labels: bug

#27 remove shar target from Makefile.
  FILES
  Makefile
Labels: development
