Repository notqmail/notqmail, pull requests merged in 2019-08, with the labels that each got.

#53 add more missing local includes
  Makefile
  predate.c
  qmail-newmrh.c
  qmail-newu.c
  qmail-pw2u.c
  qmail-qmtpd.c
  qmail-tcpto.c
  rcpthosts.c
Labels: build

#55 man rules are variously missing dependency on conf-qmail.
  Makefile
Labels: build

#42 Update docs: we're not netqmail, we're notqmail.
  CHANGES
  COPYRIGHT
  README
  UPGRADE
  VERSION
  qmail.7
Labels: documentation

#38 remove incorrect usage of vfork()
  CHANGES
  Makefile
  TARGETS
  fork.h
  fork.h1
  qmail-lspawn.c
  qmail-rspawn.c
  qmail.c
  tryvfork.c
Labels: bug

#33 remove SYSDEPS, the list of platform-specific build artifacts.
  SYSDEPS
  UPGRADE
Labels: development

#63 notqmail 1.07
  CHANGES
Labels: documentation

#80 include unistd.h in readwrite.h to declare read, write.
  readwrite.h
Labels: build

#81 include stdlib.h and stop redeclaring malloc, free in alloc.c
  alloc.c
Labels: build

#34 remove systype and attendant platform detection.
  Makefile
  README
  TARGETS
  find-systype.sh
  make-makelib.sh
  trycpp.c
Labels: build

#58 TravisCI: minor improvements
  .travis.yml
Labels: development

#46 Run alternate qmail-remote by setting QMAILREMOTE.
  CHANGES
  Makefile
  qmail-remote.8
  qmail-rspawn.8
  qmail-rspawn.c
Labels: enhancement
