Repository notqmail/notqmail, pull requests merged in 2020-11, with the labels that each got.

#119 qmail-local: close race window when creating file in tmp/
  qmail-local.c
Labels: bug

#180 add .gitattributes to keep some files out of release tarballs
  .gitattributes
Labels: development

#181 extend usage of GitHub actions for CI builds
  .github/workflows/ccpp.yml
Labels: build, development

#182 put all usernames into the same object
  Makefile
  TARGETS
Labels: development

#187 Fix 2 warnings from -Wincompatible-library-redeclaration.
  .github/workflows/ccpp.yml
  .travis.yml
  alloc.h
  deprecated.h
  qmail-send.c
  qsutil.c
  qsutil.h
Labels: build

#186 Fix 3 warnings from -Wpointer-sign.
  tcp-env.c
  timeoutconn.c
Labels: build

#185 Fix 5 warnings from -Wdangling-else.
  qmail-getpw.c
  qmail-inject.c
  qmail-local.c
  qreceipt.c
Labels: build

#188 Fix 1 warning from -Wempty-body.
  substdo.c
Labels: build

#184 Fix 17 warnings from -Wparentheses.
  auto-str.c
  case_lowers.c
  envread.c
  fmt_str.c
  hfield.c
  maildir.c
  qmail-clean.c
  qmail-qread.c
  qmail-remote.c
  qmail-send.c
  qmail-showctl.c
  qmail-smtpd.c
  received.c
Labels: build

#148 Symlink "CI" configs somewhere easier to see.
  .gitattributes
  autobuilds/cirrus.yml
  autobuilds/github.yml
  autobuilds/travis.yml
Labels: build
