Repository notqmail/notqmail, pull requests merged in 2020-12, with the labels that each got.

#192 Define CODEOWNERS with our default reviewers.
  .github/CODEOWNERS
Labels: development

#193 Fix CodeQL cpp/integer-multiplication-cast-to-long.
  qmail-send.c
Labels: bug

#183 always include the own header first in all C files
  cdbmss.c
  coe.c
  commands.c
  constmap.c
  control.c
  date822fmt.c
  dns.c
  dnsdoe.c
  env.c
  fifo.c
  fmtqfn.c
  getln.c
  gfrom.c
  headerbody.c
  hier.c
  ip.c
  ipalloc.c
  ipme.c
  maildir.c
  myctime.c
  ndelay.c
  newfield.c
  prioq.c
  prot.c
  qmail.c
  qsutil.c
  quote.c
  rcpthosts.c
  readsubdir.c
  received.c
  remoteinfo.c
  sgetopt.c
  slurpclose.c
  spawn.c
  tcpto.c
  timeoutconn.c
  timeoutread.c
  timeoutwrite.c
  token822.c
  trigger.c
  triggerpull.c
Labels: development

#61 Extract an "instqueue" program from instpackage.
  CHANGES.md
  Makefile
  TARGETS
  hier.c
  hier.h
  instfiles.c
  instpackage.c
  instqueue.c
Labels: build
