Repository notqmail/notqmail, pull requests merged in 2021-01, with the labels that each got.

#205 do not use Posix style -n argument for tail
  Makefile
Labels: bug, build

#200 Fix 3 warnings from -Wpointer-sign.
  auto-str.c
  cdbmss.c
Labels: build

#206 CI: add a test job for Solaris
  .github/workflows/solaris.yml
Labels: development

#211 add noreturn attribute to a couple of functions
  .github/workflows/ccpp.yml
  noreturn.h
  qmail-inject.c
  qmail-local.c
  qmail-popup.c
  qmail-qmtpd.c
  qmail-qread.c
  qmail-queue.c
  qmail-remote.c
  qmail-start.c
  sendmail.c
  strerr.h
  tcp-env.c
Labels: development
